using Rerout.AspNetCore;
using Rerout.AspNetCore.DependencyInjection;
using Rerout.AspNetCore.Tests;

// Minimal entry-point app hosted by WebApplicationFactory<Program>. The
// per-test ReroutWebhookFactory overrides the webhook options and handler, so
// the registrations here are only baseline placeholders.
var builder = WebApplication.CreateBuilder(args);
builder.Logging.ClearProviders();

builder.Services
    .AddRerout("rrk_default_test_key")
    .AddReroutWebhooks("whsec_default_test_secret")
    .AddReroutWebhookHandler<RecordingEventHandler>();

var app = builder.Build();
app.MapReroutWebhook("/webhooks/rerout");
app.MapGet("/health", () => "ok");
app.Run();

namespace Rerout.AspNetCore.Tests
{
    /// <summary>
    /// Public marker so <c>WebApplicationFactory&lt;Program&gt;</c> can locate the
    /// test app's entry assembly. Generated by the top-level statements above;
    /// declared here only to widen its accessibility for the test host.
    /// </summary>
    public sealed partial class Program
    {
    }
}
