require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - '.bundle/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Naming/AccessorMethodName:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: true
